# iTwin.js Docs CI Build

parameters:
  - name: forcePublish
    displayName: Publish
    type: boolean
    default: false

trigger:
  branches:
    include:
      - master
      - release/*
    exclude:
      - release/3*
      - release/2*
      - release/1*

variables:
  - group: Rush Build Cache SAS Token
  - group: Caleb - Azure Artifacts - Read-only

pr:
  drafts: false
  branches:
    include:
      - master
      - release/*
    exclude:
      - release/3*
      - release/2*
      - release/1*
  paths:
    exclude:
      - .github/CODEOWNERS

resources:
  repositories:
    - repository: build-pipeline-scripts
      type: git
      name: iModelTechnologies/imodeljs-build-pipeline-scripts

jobs:
  - template: ./docs-build.yaml
    parameters:
      workingDir: $(Pipeline.Workspace)/itwinjs-core
      outputDir: $(Agent.BuildDirectory)/tempDocsBuild/public_build
      shouldPublish: ${{ or(eq('${{parameters.forcePublish}}', true), eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')) }}
