parameters:
  - name: workingDir
    type: string
    default: $(System.DefaultWorkingDirectory)

steps:
  - script: Write-Host "Dry-run success"
    displayName: "Dry-run test"
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'Schedule', 'Manual'), eq(variables['Agent.OS'], 'Windows_NT'), eq(dependencies.CheckIfCommitIsVersionBump.outputs['isVersionBump.ShouldPublish'], 'true'))

  # - script: node common/scripts/install-run-rush.js publish --publish --pack --include-all
  #   displayName: rush publish pack
  #   workingDirectory: ${{ parameters.workingDir }}
  #   condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'Schedule', 'Manual'), eq(variables['Agent.OS'], 'Windows_NT'), eq(dependencies.CheckIfCommitIsVersionBump.outputs['isVersionBump.ShouldPublish'], 'true'))

  # - task: PythonScript@0
  #   displayName: Gather packages for release
  #   inputs:
  #     workingDirectory: ${{ parameters.workingDir }}
  #     scriptSource: filepath
  #     scriptPath: common/scripts/gather_packages.py
  #     arguments: "$(Build.ArtifactStagingDirectory) $(Build.SourcesDirectory) $(Build.SourceBranch)"
  #   condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'Schedule', 'Manual'), eq(variables['Agent.OS'], 'Windows_NT'), eq(dependencies.CheckIfCommitIsVersionBump.outputs['isVersionBump.ShouldPublish'], 'true'))

  # - task: PublishBuildArtifacts@1
  #   displayName: "Publish Artifact: packages"
  #   inputs:
  #     PathtoPublish: "$(Build.ArtifactStagingDirectory)/imodeljs/packages"
  #     ArtifactName: packages
  #   condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'Schedule', 'Manual'), eq(variables['Agent.OS'], 'Windows_NT'), eq(dependencies.CheckIfCommitIsVersionBump.outputs['isVersionBump.ShouldPublish'], 'true'))
